services:
  app:
    build: .
    container_name: express_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://<other_project_mongo_host>:27017/coursesDB  # Point to the correct MongoDB instance
    volumes:
      - .:/app
      - /app/node_modules
